### ISSUE TITLE
documentation/v3/mediasoup/api/ directory not exist 

### ISSUE THREAD

**Issue by aggresss** [versatica/mediasoup-website#18]
https://github.com/versatica/mediasoup-website/blob/master/documentation/v3/mediasoup/api.md

```
include documentation/v2/mediasoup/api/xx.md
include documentation/v3/mediasoup/api/xx.md
```
But no exist documentation/v3/mediasoup/api/ directory

**Comment by ibc** [comment]
But it works, right?
