### ISSUE TITLE
Front-page uses the SFU acronym without explanation

### ISSUE THREAD

**Issue by andybak** [versatica/mediasoup-website#20]
I'm going to presume it's not "Single Family Unit", "Société Française des Urbanistes" or any of the other things my search has suggested.

Be kind to us and go easy on the TLAs, eh?

**Comment by ibc** [comment]
PR welcome. If you don't know what a SFU means in the context of audio/video real-time communication probably mediasoup is not for you.

**Comment by andybak** [comment]
Nice. That's not the tone of response I was expecting.
