### ISSUE TITLE
TOC on API documentation pages is not working.

### ISSUE THREAD

**Issue by adaohenrique** [versatica/mediasoup-website#31]
The table of contents (side menu) on the API documentation pages (e.g.: https://mediasoup.org/documentation/v3/mediasoup/api/) stopped working somewhere in the last couple of days. The problem is related to the AnchorJS library initialization.

I created a PR that seems to fix it: https://github.com/versatica/mediasoup-website/pull/30

**Comment by jmillan** [comment]
Thanks @adaohenrique,

We'll take a look at it ASAP.

**Comment by ibc** [comment]
Issue fixed here: https://github.com/versatica/mediasoup-website/commit/689804748c984d090e28f9ba6a9c1ea3a055b67c
