### ISSUE TITLE
Device `close` event doesn't exists

### ISSUE THREAD

**Issue by piranna** [versatica/mediasoup-website#40]
As shown at https://mediasoup.discourse.group/t/are-close-events-in-mediasoup-client-replicated-from-server-side/3881/5?u=piranna and https://mediasoup.discourse.group/t/are-close-events-in-mediasoup-client-replicated-from-server-side/3881/8?u=piranna, mediasoup-client `Device` shows a [`close` event](https://mediasoup.org/documentation/v3/mediasoup-client/api/#router-observer-on-close) that doesn't exist in the actual implementation, the same that there's no `close()` method at all to be called. Based on the anchor of the URL, seems like it was copy&pasted from Mediasoup documentation, this needs to be removed.

**Comment by ibc** [comment]
Thanks, fixed and deployed.

**Comment by piranna** [comment]
> Thanks, fixed and deployed.

You are welcome :-)

As a side note, would have it made sense to keep it, and instead add a `close()` method?

**Comment by ibc** [comment]
No, there is nothing to close in the `Device` class. It's just a holder and it will be probably removed in mediasoup-client v4.

**Comment by piranna** [comment]
> No, there is nothing to close in the `Device` class. It's just a holder and it will be probably removed in mediasoup-client v4.

Ok, thanks for the clarification :-)
