### ISSUE TITLE
`workerBin` is not documented

### ISSUE THREAD

**Issue by piranna** [versatica/mediasoup-website#51]
Has it been deprecated? Or moved to private API?

**Comment by ibc** [comment]
Done here https://github.com/versatica/mediasoup-website/commit/ea46a0a8c6e817ab03b9cf40e6279c869c2699a5

https://mediasoup.org/documentation/v3/mediasoup/api/#workerBin

**Comment by piranna** [comment]
I've reviewed this, and it's published as a constant under `Worker` class, but it's exposed by `mediasoup` instance, shouldn't the constants paragraph be put there instead?

**Comment by ibc** [comment]
All types and classes are exported by `mediasoup.types` and none of them are documented by explicitly saying that. Nothing new here. Not just for `workerBin` but also `WebRtcTransportOptions` etc etc.

https://mediasoup.org/documentation/v3/mediasoup/api/#mediasoup-types

I'm improving it as follows:

> An Object holding all classes, utils, **TypeScript** types and constants exported by mediasoup.

**Comment by ibc** [comment]
Note: I'm moving it to `Properties` section in root module docs.
