### ISSUE TITLE
`createWebRtcServer()` don't allow `listenInfo`s to be `string`

### ISSUE THREAD

**Issue by piranna** [versatica/mediasoup-website#52]
At https://mediasoup.org/documentation/v3/mediasoup/api/#WebRtcServerOptions, `listenInfos` is documented as `Array<[TransportListenInfo](https://mediasoup.org/documentation/v3/mediasoup/api/#TransportListenInfo)|String>`, but at https://github.com/versatica/mediasoup/blob/bf7a3973f93282a3d296c8702ddad53c368076a8/node/src/Worker.ts#L692-L709, `listInfo` as string is ignored, allowing it to only be defined as a [TransportListenInfo](https://mediasoup.org/documentation/v3/mediasoup/api/#TransportListenInfo).

**Comment by ibc** [comment]
Done.

**Comment by piranna** [comment]
Great, thanks :-)
